packages:
  - 'ceo-escalavel-miniapp'
  - 'flow-links-bio'
  - 'neo-flowoff-agency'
  - 'neo-flowoff-pwa'
  - 'neo-flw-landing'
  - 'neo-landing-open'
  - 'neoflow-content-machine'
  - 'neoflowoff-chat-ui'
  - 'neoflw-token'
  - 'neoflw-token-page'
  - 'pro-ia'

overrides:
  'express>path-to-regexp': '0.1.13'
  'anymatch>picomatch': '^2.3.2'
  'readdirp>picomatch': '^2.3.2'
  'micromatch>picomatch': '2.3.2'
  'tinyglobby>picomatch': '4.0.4'
  'vite>picomatch': '4.0.4'
  'vitest>picomatch': '4.0.4'
  'minimatch>brace-expansion': '^5.0.5'
  tar: '^7.5.4'
  minimatch: '^9.0.5'
  undici: '^7.24.0'
  picomatch: '^2.3.2'
  path-to-regexp: '^8.4.0'
  lodash: '^4.18.0'
  flatted: '^3.4.2'
  socket.io-parser: '^4.2.6'
  yaml: '^2.8.3'
  axios: '^1.15.0'
  rollup: '^4.59.0'
  ajv: '^6.14.0'
  brace-expansion: '^2.0.3'
  vite: '^7.3.2'

onlyBuiltDependencies:
  - '@reown/appkit'
  - '@scarf/scarf'
  - bufferutil
  - esbuild
  - keccak
  - secp256k1
  - sharp
  - unrs-resolver
  - utf-8-validate
  - typescript-eslint
  - sharp-libvips-darwin-arm64
  - wordnet-db
  - solc
  - next
  - edr-win32-x64-msvc
