packages:
  - "flow-links-bio"
  - "ceo-escalavel-miniapp"
  - "neo-digitalfather"
  - "neo-flowoff-agency"
  - "neo-flowoff-pwa"
  - "neo-flowoff-pwa/frontend"
  - "neo-growth-sdr-landing"
  - "neo-flw-landing"
  - "neo-landing-open"
  - "neo-shared"
  - "neoflow-content-machine"
  - "neoflowoff-chat-ui"
  - "neoflw-token"
  - "neoflw-token-page"
  - "pro-ia"

overrides:
  encoding-sniffer: "^1.0.2"
  "express>path-to-regexp": "0.1.13"
  "anymatch>picomatch": "^2.3.2"
  "readdirp>picomatch": "^2.3.2"
  "micromatch>picomatch": "2.3.2"
  "tinyglobby>picomatch": "4.0.4"
  "vite>picomatch": "4.0.4"
  "vitest>picomatch": "4.0.4"
  tar: "^7.5.4"
  picomatch: "^2.3.2"
  path-to-regexp: "^8.4.0"
  lodash: "^4.18.0"
  flatted: "^3.4.2"
  socket.io-parser: "^4.2.6"
  yaml: "^2.8.3"
  axios: "^1.15.0"
  rollup: "^4.59.0"
  ajv: "^6.14.0"

allowBuilds:
  "@reown/appkit": true
  "@scarf/scarf": true
  bufferutil: true
  esbuild: true
  keccak: true
  secp256k1: true
  sharp: true
  unrs-resolver: true
  utf-8-validate: true
  typescript-eslint: true
  sharp-libvips-darwin-arm64: true
  wordnet-db: true
  solc: true
  next: true
  edr-win32-x64-msvc: true

minimumReleaseAgeExclude:
  - "@neo-flowoff/shared@1.0.0"

peerDependencyRules:
  allowedVersions:
    eslint-plugin-react>eslint: '10'
    fdir>picomatch: '4.0.4'
    '@nomicfoundation/hardhat-verify>hardhat': '2.28.6'
    '@nomicfoundation/hardhat-toolbox>@nomicfoundation/hardhat-verify': '3.0.20'
    '@nomicfoundation/hardhat-ignition>@nomicfoundation/hardhat-verify': '3.0.20'
    '@nomicfoundation/hardhat-toolbox>@types/chai': '5.2.3'
    '@nomicfoundation/hardhat-toolbox>chai': '6.2.2'
    '@nomicfoundation/hardhat-chai-matchers>chai': '6.2.2'
    'chai-as-promised>chai': '6.2.2'
    ws>utf-8-validate: '6.0.6'
    '@farcaster/quick-auth>typescript': '5.9.3'
    '@farcaster/miniapp-wagmi-connector>@farcaster/miniapp-sdk': '0.1.10'
    use-sync-external-store>react: '19.2.7'
    tailwindcss-animate>tailwindcss: '3.4.19'
    '@wagmi/core>typescript': '5.8.3'
    '@wagmi/connectors>typescript': '5.8.3'
    'wagmi>typescript': '5.8.3'
    'abitype>zod': '4.4.3'
    'lucide-react>react': '19.0.0'
    'next>react': '19.0.0'
    'next>react-dom': '19.0.0'
    '@eslint/js>eslint': '9.39.4'
allowedDeprecatedVersions:
  request: "*"
